### PR TITLE
Added table arg to query methods.

### PR DESCRIPTION
**Pull request by jcpunk**
This allows me to more easily group the table with the query.

### CODE REVIEW

**Comment by rbw0** [comment]
Hello jcpunk!

First, thanks for your proposed addition.
I'd like keep things clean and consistent when it comes to usage.
I'm not saying the way I choose to build this piece of software is right and the best for everyone, but, while being able to do things in multiple ways might be good in terms of flexibility, it does introduce an increased code complexity, especially in the long run, which increases the risk for bugs and also potentially confusion for the user. Not saying this particular change likely causes things to break, but multiple similar implementations might.
And I'm not saying there's anything wrong doing it this way, but is it really needed?

Could you give some examples of how you'd do this with and without your change? Perhaps doing it your way as the only way is better.

Just trying to keep things simple. Anyone else with opinions perhaps?

Small change, long answer :)

Regards,
Robert

**Comment by jcpunk** [comment]
I'm performing a large number of queries (about 400) over various tables (12).  My worst query takes about 90 seconds to return, my best about 10.  In order to speed things up I'm beginning to look at what it would take to make this module mostly thread safe (concurrent.futures submit is my end target).  Getting it thread safe for query operations should be very doable.

As I see it the primary hurdle is the table selection.  If we can get the api call to be "atomic(ish)" the rest should just work.

This is step 1, get the args into place.
Step 2 is probably some fairly simplistic RLocks.

If you are open to moving the table into the function arg only that would simplify things greatly.  Failing that, my initial thoughts were around the @ property decorator for the table selection.

**Comment by rbw0** [comment]
FYI 075367e0f48171fbe484d290cf15dece30d508c5

**Comment by rbw0** [comment]
Note that it's in testing right now

**Pull request closed without merging**
